# Generated by Django 5.2.6 on 2025-11-21 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scraping', '0005_noticiasvistas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalisisNoticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resumen', models.TextField(blank=True, null=True)),
                ('sentimiento', models.CharField(blank=True, max_length=20, null=True)),
                ('sentimiento_confianza', models.FloatField(default=0.0)),
                ('categoria', models.CharField(blank=True, max_length=100, null=True)),
                ('entidades', models.JSONField(blank=True, default=dict)),
                ('palabras_clave', models.JSONField(blank=True, default=list)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('completado', 'Completado'), ('error', 'Error')], default='pendiente', max_length=20)),
                ('tokens_usados', models.IntegerField(default=0)),
                ('coste_estimado', models.DecimalField(decimal_places=4, default=0.0, max_digits=6)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('noticia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analisis', to='scraping.noticia')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Análisis de Noticia',
                'verbose_name_plural': 'Análisis de Noticias',
                'ordering': ['-creado_en'],
            },
        ),
    ]
