# Generated by Django 5.2.6 on 2025-11-21 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisisnoticia',
            name='task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
