# Generated by Django 5.2.6 on 2025-11-21 16:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis', '0002_analisisnoticia_task_id'),
        ('scraping', '0005_noticiasvistas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='analisisnoticia',
            index=models.Index(fields=['usuario', 'estado'], name='analisis_an_usuario_ec92e9_idx'),
        ),
    ]
