# Generated by Django 5.2.6 on 2025-11-21 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis', '0003_analisisnoticia_analisis_an_usuario_ec92e9_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='analisisnoticia',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='analisis', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
