# Generated by Django 5.2.6 on 2025-11-21 20:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis', '0004_alter_analisisnoticia_usuario'),
        ('scraping', '0005_noticiasvistas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='analisisnoticia',
            name='noticia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analisis', to='scraping.noticia'),
        ),
        migrations.AlterUniqueTogether(
            name='analisisnoticia',
            unique_together={('noticia', 'usuario')},
        ),
        migrations.AddIndex(
            model_name='analisisnoticia',
            index=models.Index(fields=['noticia', 'usuario'], name='analisis_an_noticia_b6f0d5_idx'),
        ),
    ]
