# Generated by Django 5.2.6 on 2025-11-21 20:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis', '0005_alter_analisisnoticia_noticia_and_more'),
        ('scraping', '0005_noticiasvistas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='analisisnoticia',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='analisisnoticia',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'completado')), fields=('noticia', 'usuario'), name='unique_analisis_completado_por_usuario'),
        ),
    ]
