# Generated by Django 5.2.6 on 2025-11-21 20:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis', '0006_alter_analisisnoticia_unique_together_and_more'),
        ('scraping', '0005_noticiasvistas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='analisisnoticia',
            name='unique_analisis_completado_por_usuario',
        ),
        migrations.AddConstraint(
            model_name='analisisnoticia',
            constraint=models.UniqueConstraint(fields=('noticia', 'usuario'), name='unique_analisis_por_usuario'),
        ),
    ]
