# Generated by Django 5.2.6 on 2025-11-21 20:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analisis', '0007_remove_analisisnoticia_unique_analisis_completado_por_usuario_and_more'),
        ('scraping', '0005_noticiasvistas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='analisisnoticia',
            name='unique_analisis_por_usuario',
        ),
        migrations.RemoveIndex(
            model_name='analisisnoticia',
            name='analisis_an_noticia_b6f0d5_idx',
        ),
        migrations.AlterUniqueTogether(
            name='analisisnoticia',
            unique_together={('noticia', 'usuario')},
        ),
    ]
