# Generated by Django 5.2.6 on 2025-09-12 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('autor', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('imagen', models.TextField(blank=True, null=True)),
                ('enlace', models.TextField(blank=True, null=True)),
                ('fecha_scraping', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fecha', '-fecha_scraping'],
            },
        ),
    ]
