# Generated by Django 5.2.6 on 2025-09-23 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='origen',
            field=models.CharField(default='desconocido', max_length=100),
        ),
    ]
