# Generated by Django 5.2.6 on 2025-09-23 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0002_noticia_origen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='origen',
            field=models.CharField(default='elcomercio', max_length=100),
        ),
    ]
