# Generated by Django 5.2.6 on 2025-11-10 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0003_alter_noticia_origen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='origen',
            field=models.CharField(default='desconocido', max_length=100),
        ),
    ]
