# Generated by Django 5.2.6 on 2025-11-13 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('normal', 'Usuario Normal'), ('premium', 'Usuario Premium'), ('admin', 'Administrador')], default='normal', max_length=10),
        ),
    ]
