# Generated by Django 5.2.6 on 2025-11-17 22:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_fecha_registro'),
        ('scraping', '0005_noticiasvistas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('vista', 'Vio noticia'), ('busqueda', 'Realizó búsqueda'), ('compartir', 'Compartió noticia'), ('login', 'Inició sesión'), ('scraping', 'Ejecutó scraping')], max_length=20)),
                ('descripcion', models.TextField()),
                ('datos_extra', models.JSONField(blank=True, default=dict)),
                ('fecha_actividad', models.DateTimeField(auto_now_add=True)),
                ('noticia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scraping.noticia')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Actividades',
                'ordering': ['-fecha_actividad'],
            },
        ),
    ]
